<a href="https://colab.research.google.com/github/Indahnalz/Tugas-Algoritma/blob/main/2208541035_IndahNurAliza_TugasV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5.16 List 2 Dimensi
##pertemuan tanggal 03 April 2023

Pendahuluan
adalah menempatkan sebuah list di dalam list.
Penggambarannya seperti sebuah matrik.

In [ ]:
# buat lah matrik sederhana
matrik = [
    [2,3,5,7],
    [4,6,8,10],
    [11,12,13,14],
    [15,17,19,21],
]

print(matrik)

[[2, 3, 5, 7], [4, 6, 8, 10], [11, 12, 13, 14], [15, 17, 19, 21]]


In [ ]:
# panggil variabel matrik di baris pertama dengan perintah berikut
matrik[1]

[4, 6, 8, 10]

In [ ]:
# selanjutnya kita akan mencoba variabel matrik dibaris pertama dan kedua
matrik[1][2]

13

In [ ]:
# selanjutnya kita akan mencoba mengubah hasil dari variabel matrik di baris pertama dan kedua
matrik[1][2] = 18
print(matrik[1][2])

18


In [ ]:
# disini kita akan mengambil semua nilai keseluruhan dari variabel matrik
matrik

[[2, 3, 5, 7], [4, 6, 18, 10], [11, 12, 13, 14], [15, 17, 19, 21]]

In [ ]:
# lalu, kita akan memanggil nilai dari variabel matrik
for baris in matrik:
  print(baris)
  for kolom in baris:
    print(kolom)


[2, 3, 5, 7]
2
3
5
7
[4, 6, 18, 10]
4
6
18
10
[11, 12, 13, 14]
11
12
13
14
[15, 17, 19, 21]
15
17
19
21


In [ ]:
# latihan 2
huruf = ("a","b","c","d","e")

In [ ]:
# memanggil nilai kedua dari variabel huruf 
huruf[2]

'c'

In [ ]:
#memanggil nilai ke nol-ke tiga dari variabel huruf
huruf[0:3]

('a', 'b', 'c')

In [ ]:
#menampilkan semua isi dari varibel huruf
for isi in huruf:
 print(isi)

a
b
c
d
e


# 5.17 Tuples
Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. 

In [ ]:
angka = (3,5,7,8,8,9)

In [ ]:
# mencetak angka pertama
print(angka[1])

5


In [ ]:
# mencetak angka ke nol sampai ke dua namun yang kedua tidak ikut di tampilkan 
print(angka[0:2])

(3, 5)


In [ ]:
for isi in angka[0:2]:
 print(isi)

3
5


In [ ]:
#mengubah nilai di variabel angka
angka = 10

#saat di run akan tampak berhasil, namun sebenarnya nilai tsb tidak benar" diubah ke variabel angka

In [ ]:
# saat menggunakan perintah append, varibel angka akan error saat dirun
angka.append(10)
# hal ini menunjukkan bahwa nilai varibel tidak bisa diubah sama sekali walaupun data nilai sudah di ganti

AttributeError: ignored

In [ ]:
#kembali lagi pada definisi tuples yaitu bahwa data nilai tidak bisa dirubah/dihapus isinya
angka.remove(3)

AttributeError: ignored

In [ ]:

# fungsi count adalah untuk menghitung berapa kali munculnya objek dalam suatu elemen yg berada di list
angka.count(8)

2

In [ ]:
# fungsi index adalah untuk menemukan posisi suatu elemen dalam objek/variabel
angka.index(3)

0

In [ ]:
# Latihan 2
# Membuat tuples

fruit = ("apple", "banana", "cherry")


# Mengakses elemen tuples

print(fruit[0])

print(fruit[1])

print(fruit[2])

apple
banana
cherry


In [ ]:
# Menambah tuples

buah= fruit + ("mango",)

print(buah)

('apple', 'banana', 'cherry', 'mango')


In [ ]:
# Menghapus tuples

del fruit

print(fruit)

#perintah ini akan menghasilkan error karena tuple sudah di hapus

NameError: ignored

In [ ]:

# Latihan 3
# membuat tuples dengan nama-nama bulan

bulan = ("Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember",)

In [ ]:
# menampilkan isi dari tuples

print(bulan)

('Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember')


In [ ]:
# mengakses elemen tuples menggunakan indeks

print(bulan[0]) 

print(bulan[7])

Januari
Agustus


In [ ]:
# tuples bersifat immutable (tidak dapat diubah)

bulan[0] = "New Year"

TypeError: ignored

In [ ]:
# mencari indeks dari sebuah elemen di dalam tuple

print(bulan.index("Juli")) #

6


In [ ]:
# menghitung jumlah kemunculan suatu elemen di dalam tuple

print(bulan.count("Juni"))

1


# 5.18 Dictionaries
## Pendahuluan :
Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut.

In [ ]:
data_pribadi = {
 "Nama" : "Byun Baekhyun",
"Umur" : 30,
"Apakah_WNI" : "False"
}

In [ ]:
# kita akan menampilkan "Nama" dari variabel data pribadi
print(data_pribadi["Nama"])

Byun Baekhyun


In [ ]:
print(data_pribadi["nama"])
# perintah ini akan menghasilkan error karena penginisialisasinya tidak sesuai dengan data pribadi

KeyError: ignored

In [ ]:
#fungsi .get digunakan untuk mengambil nilai dari sebuah kunci (key) yang ada pada sebuah dictionary.
print(data_pribadi.get("Nama"))

Byun Baekhyun


In [ ]:

# perintah ini sama dengan sebelumnya, namun ini akan menampilkan none karena tidak ada data dalam "nama"
print(data_pribadi.get("nama"))

None


In [ ]:
# perintah ini digunakan untuk mendapatkan data "tanggal lahir" namun, karena tidak ada data tentang "tanggal lahir" maka perintah ini akan menghasilkan "none"
print(data_pribadi.get("tanggal_lahir"))

None


In [ ]:
# perintah ini merupakan lanjutan dari perintah diatas, dimana kita menambahkan nilai data pada "tanggal lahir"
print(data_pribadi.get("tanggal_lahir","6-5-1992"))

6-5-1992


In [ ]:
# menampilkan keseluruhan data dalam "data pribadi"
print(data_pribadi)

{'Nama': 'Byun Baekhyun', 'Umur': 30, 'Apakah_WNI': 'False'}


In [ ]:
print(data_pribadi["tanggal_lahir"])

KeyError: ignored

In [ ]:

# menambahkan data "HP" kedalam "data pribadi"
data_pribadi["HP"] = "087881392898"

In [ ]:
print(data_pribadi["HP"])

087881392898


In [ ]:
print(data_pribadi)

{'Nama': 'Byun Baekhyun', 'Umur': 30, 'Apakah_WNI': 'False', 'HP': '087881392898'}


In [ ]:
# Latihan 2
# membuat dictionary kosong

person = {}

In [ ]:
# menambahkan data ke dalam dictionary

person["name"] = "Ryu Sung Jun"

person["age"] = 28

person["address"] = "Jakarta"

In [ ]:
# menampilkan data pada dictionary

print(person)

{'name': 'Ryu Sung Jun', 'age': 28, 'address': 'Jakarta'}


In [ ]:
# mengakses nilai pada dictionary menggunakan kunci

print(person["name"])
print(person["age"])

Ryu Sung Jun
28


In [ ]:
# mengubah nilai pada dictionary menggunakan kunci

person["age"] = 23

In [ ]:
# menghapus data pada dictionary menggunakan kunci

del person["address"]

In [ ]:
# menampilkan data pada dictionary setelah diubah dan dihapus

print(person)

{'name': 'Ryu Sung Jun', 'age': 23}


In [ ]:
# membuat dictionary dengan beberapa elemen

students = {"zayn": 80, "harry": 90, "jake": 75, "mark": 85}

In [ ]:
# menampilkan nilai pada dictionary menggunakan kunci

print(students["zayn"])

print(students["harry"])

80
90


In [ ]:
# menampilkan semua kunci pada dictionary

print(students.keys())

dict_keys(['zayn', 'harry', 'jake', 'mark'])


In [ ]:
# menampilkan semua nilai pada dictionary

print(students.values())

dict_values([80, 90, 75, 85])


In [ ]:
# menampilkan pasangan kunci dan nilai pada dictionary

print(students.items())

dict_items([('zayn', 80), ('harry', 90), ('jake', 75), ('mark', 85)])


 # 5.19 Fungsi dalam Python

## Pendahuluan
Pada dasarnya fungsi
dibentuk untuk menghidari pengulangan pembuatan program secara manual
dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat,
setiap fungsi tersebut dibutuhkan tinggal kita panggil.

In [ ]:

# menginput nama lengkap
def full_nama(first_name,last_name):
  print(f"Nama lengkapnya adalah {nama_depan} {nama_belakang}")
  
first_name = input("Nama depan saya adalah ")
last_name = input("Nama belakang saya adalah ")
full_nama = input("nama_depan,nama_belakang ")

In [ ]:
# latihan 2
#disini kita akan menghitung keliling persegi panjang
def hitung_keliling_bangunan():
    sisi1 = float(input("Masukkan panjang sisi 1: "))
    sisi2 = float(input("Masukkan panjang sisi 2: "))
    sisi3 = float(input("Masukkan panjang sisi 3: "))
    sisi4 = float(input("Masukkan panjang sisi 4: "))
    keliling = sisi1 + sisi2 + sisi3 + sisi4
    return keliling

def cek_persegi_panjang():
    sisi1 = float(input("Masukkan panjang sisi 1: "))
    sisi2 = float(input("Masukkan panjang sisi 2: "))
    if sisi1 == sisi2:
        print("Bangunan tersebut merupakan persegi.")
    else:
        print("Bangunan tersebut merupakan persegi panjang.")

keliling_bangunan = hitung_keliling_bangunan()
print("Keliling bangunan tersebut adalah", keliling_bangunan)
cek_persegi_panjang()

# 5.19.1 Tugas Fungsi pada Python

In [ ]:

# menghitung luas segitiga
def hitung_luas_segitiga(alas, tinggi):
    luas = 0.5 * alas * tinggi
    return luas
#mencetak luas segitiga
luas_segitiga = hitung_luas_segitiga(5, 7)
print(luas_segitiga)

17.5


In [ ]:
#kita mengimpor modul math, yang digunakan untuk menghitung nilai-nilai matematika seperti akar kuadrat dan pi.
import math 
#mendefinisikan fungsi hitung_luas_layang_layang
def hitung_luas_layang_layang():
    diagonal1 = float(input("Masukkan panjang diagonal 1: "))
    diagonal2 = float(input("Masukkan panjang diagonal 2: "))
    luas = (diagonal1 * diagonal2) / 2
    return luas
#mencetak luas layang-layang
hitung_luas_layang_layang()
print("Luas layang-layang tersebut adalah", luas_layang_layang)

In [ ]:
import math 
def hitung_luas_jajar_genjang():
    alas = float(input("Masukkan panjang alas: "))
    tinggi = float(input("Masukkan tinggi: "))
    luas = alas * tinggi
    return luas
luas_jajar_genjang = hitung_luas_jajar_genjang()
print("Luas jajar genjang tersebut adalah", luas_jajar_genjang)

In [ ]:
import math 
def hitung_luas_kerucut():
    jari_jari = float(input("Masukkan jari-jari: "))
    tinggi = float(input("Masukkan tinggi: "))
    luas_selimut = math.pi * jari_jari * math.sqrt(jari_jari**2 + tinggi**2)
    luas_alas = math.pi * jari_jari**2
    luas = luas_selimut + luas_alas
    return luas
luas_kerucut = hitung_luas_kerucut()
print("Luas kerucut tersebut adalah", luas_kerucut)

# 5.20 Numpy
## Pendahuluan

Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi

In [ ]:
import pandas as pd

## 5.20.1 Perintah dasar pada numpy

mengetahui dimensi dan ukuran variabel

In [ ]:
import numpy as np

In [ ]:
# membuat variabel
a = np.array([3,8,11,13])
# mencetak variabel a
print(a)

[ 3  8 11 13]


In [ ]:
# membuat variabel b
b = np.array([[3,7,8,9],[2,4,1,9]])
# mengakses variabel b
print(b)

[[3 7 8 9]
 [2 4 1 9]]


In [ ]:
# membuat variabel c
c = np.array([[[0,1,2,3],[4,5,6,7],[8,9,2,3],[4,9,8,7],[3,5,7,9],[2,4,6,8]]])
# mengakses variabel c
print(c)

[[[0 1 2 3]
  [4 5 6 7]
  [8 9 2 3]
  [4 9 8 7]
  [3 5 7 9]
  [2 4 6 8]]]


In [ ]:
# .ndim berfungsi untuk mengembalikan jumlah dimensi atau rank dari sebuah array.
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
c.ndim

3

In [ ]:
# .shape berfungsi untuk mengembalikan tuple yang berisi jumlah elemen pada setiap dimensi dari sebuah array NumPy.
a.shape

(4,)

In [ ]:
b.shape

(2, 4)

In [ ]:
c.shape

(1, 6, 4)

In [ ]:

#latihan 2
import numpy as np

# membuat array 1 dimensi dengan 6 elemen
arr1 = np.array([1, 2, 3, 4, 5, 6])

# mengubah bentuk array menjadi matriks 2x3
arr2 = arr1.reshape(2, 3)
print(arr2)
# Output: 
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [ ]:

#latihan 3
import numpy as np

# membuat dua array 1 dimensi
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# penjumlahan elemen dari kedua array
arr3 = arr1 + arr2
print(arr3)
# Output: [5 7 9]

# pengurangan elemen dari kedua array
arr4 = arr2 - arr1
print(arr4)
# Output: [3 3 3]

# perkalian

[5 7 9]
[3 3 3]


In [ ]:
# latihan 4
import numpy as np

# membuat array 2 dimensi (matriks)
arr = np.array([[1, 2, 3], [4, 5, 6]])

# mengetahui jumlah dimensi dari array
print(arr.ndim)  # akan mencetak 2

# mengetahui jumlah baris dan kolom dari array
print(arr.shape)  # akan mencetak (2, 3)

2
(2, 3)


# 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

Program memanggil anggota, kolom dan baris dalam list menggunakan Numpy

In [ ]:
# membuat array
d = np.array([[1,3,5,7],[2,4,6,8],[4,5,6,7]])
print(d)

In [ ]:
d[0,3]

7

In [ ]:
d[1,:]

array([2, 4, 6, 8])

In [ ]:
d[:,3]

array([7, 8, 7])

In [ ]:
d[1,0:3]

array([2, 4, 6])

In [ ]:
d[0,0:3:2]

array([1, 5])

In [ ]:
d[0,0] = 100
print(d)

[[100   3   5   7]
 [  2   4   6   8]
 [  4   5   6   7]]


In [ ]:
# latihan 2
import numpy as np

# membuat sebuah array 2 dimensi dengan bentuk 3x3
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# memanggil anggota array pada baris ke-1, kolom ke-2
print(arr[1, 2])  # output: 6

# memanggil kolom ke-0
print(arr[:, 0])  # output: [1 4 7]

# memanggil baris ke-2
print(arr[2, :])  # output: [7 8 9]

6
[1 4 7]
[7 8 9]


# 5.20.3 Matrix pada Numpy

Numpy dapat digunakan untuk membuat berbagai jenis matrix

In [ ]:
# np.ones adalah sebuah fungsi dalam library NumPy pada Python yang digunakan untuk membuat sebuah array dengan isi elemen yang seluruhnya bernilai 1.
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.zeros adalah sebuah fungsi dalam library NumPy pada Python yang digunakan untuk membuat sebuah array dengan isi elemen yang seluruhnya bernilai 0.
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# np.identity adalah sebuah fungsi dalam library NumPy pada Python yang digunakan untuk membuat sebuah matriks identitas dengan ukuran tertentu.
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.ones((7,8,9))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1

In [ ]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [ ]:
# np.random.rand adalah sebuah fungsi dalam library NumPy pada Python yang digunakan untuk menghasilkan array dengan nilai acak dalam rentang [0, 1) dengan distribusi seragam (uniform distribution).
np.random.rand(4,3)

array([[0.45052755, 0.29451953, 0.9252045 ],
       [0.58321248, 0.86887887, 0.93427595],
       [0.15115153, 0.50306455, 0.10771353],
       [0.52211767, 0.07915096, 0.11862241]])

In [ ]:

# np.random.randint adalah sebuah fungsi dalam library NumPy pada Python yang digunakan untuk menghasilkan array dengan nilai integer acak dalam rentang tertentu.
np.random.randint(1,10,size=(3,4))

array([[6, 9, 8, 7],
       [2, 9, 2, 4],
       [1, 7, 9, 2]])

In [ ]:
 # Latihan 2
import numpy as np

# Membuat matrix 2x3
A = np.array([[1, 2, 3], [4, 5, 6]])

# Membuat matrix 3x2
B = np.array([[7, 8], [9, 10], [11, 12]])

# Mengalikan matrix A dan B
C = np.dot(A, B)

# Menampilkan matrix C
print(C)

[[ 58  64]
 [139 154]]


In [ ]:
# latihan 3 
import numpy as np

# Membuat matrix 2x3
A = np.array([[1, 2, 3], [4, 5, 6]])

# Membuat matrix 3x2
B = np.array([[7, 8], [9, 10], [11, 12]])

# Mengalikan matrix A dan B
C = np.dot(A, B)

# Menampilkan matrix C
print(C)

[[ 58  64]
 [139 154]]


In [ ]:
# latihan 4
import numpy as np

# Membuat matrix 13x13 dengan nilai acak dari 0 sampai 9
matriks = np.random.randint(1, 9, size=(13, 13))

# Menampilkan matrix
print(matriks)

[[6 8 1 2 6 8 3 4 6 6 1 6 3]
 [5 7 5 1 4 3 6 1 2 2 2 7 7]
 [6 4 1 4 1 6 2 3 8 3 3 8 3]
 [6 3 3 5 4 3 4 5 6 8 4 1 7]
 [3 7 5 3 8 7 6 7 5 4 8 5 4]
 [4 4 3 8 7 5 6 3 4 2 6 6 2]
 [8 5 6 2 5 6 3 5 7 4 7 4 4]
 [2 2 7 5 5 4 8 1 8 5 3 8 5]
 [8 4 7 2 3 8 5 3 6 3 1 4 3]
 [2 3 7 6 3 4 4 7 1 2 3 7 7]
 [3 3 7 3 3 4 6 8 7 8 4 1 7]
 [1 1 7 2 6 8 2 8 1 3 8 7 5]
 [1 3 3 8 8 4 1 3 5 3 4 1 8]]


# 5.20.4 Copy pada Numpy

saat anggota variabel baru dirubah,
dampaknya juga akan merubah variabel asal. Untuk menghindari perubahan
variabel awal yang tidak dikehendaki maka diperlukan perintah copy

In [ ]:
# membuat array
a = np.array([1,2,3,4,5])
# mencetak array
print(a)

[1 2 3 4 5]


In [ ]:

# membuat array b dari array a
b = a
# mencetak array
print(b)

[1 2 3 4 5]


In [ ]:

# mengubah nilai array 
b[0] = 10
print(b)

[10  2  3  4  5]


In [ ]:
print(a)

[10  2  3  4  5]


In [ ]:
c = np.array([1,2,3,4,5])
print(c)

[1 2 3 4 5]


In [ ]:

# membuat array menggunakan .copy()
d = c.copy()
print(d)

[1 2 3 4 5]


In [ ]:
d[0] = 10
print(d)

[10  2  3  4  5]


In [ ]:
print(c)

[1 2 3 4 5]


In [ ]:
# Latihan 2
import numpy as np

# Membuat array NumPy
array1 = np.array([1, 2, 3, 4, 5])

# Melakukan copy array
array2 = array1.copy()

# Menampilkan hasil copy
print("Hasil copy array1: ", array2)

Hasil copy array1:  [1 2 3 4 5]


In [ ]:
# latihan 3
import numpy as np

# Membuat array NumPy
array1 = np.array([[1, 2, 3], [4, 5, 6]])

# Melakukan copy array
array2 = np.copy(array1)

# Menampilkan hasil copy
print("Hasil copy array1: ")
print(array2)

Hasil copy array1: 
[[1 2 3]
 [4 5 6]]


# 5.20.5 Operasi Matematika pada Numpy

In [ ]:

# penjumlahan
a+2

array([3, 4, 5])

In [ ]:

# pengurangan
a-2

array([-1,  0,  1])

In [ ]:

# perkalian
a*3

array([3, 6, 9])

In [ ]:

# pembagian
a/2

array([0.5, 1. , 1.5])

In [ ]:

# perpangkatan
a**2

array([1, 4, 9])

In [ ]:
b = np.array([6,7,8])
print(b)

[6 7 8]


In [ ]:
a+b

array([ 7,  9, 11])

In [ ]:
a-b

array([-5, -5, -5])

In [ ]:
a*b

array([ 6, 14, 24])

In [ ]:
a/b

array([0.16666667, 0.28571429, 0.375     ])

In [ ]:
a**b

array([   1,  128, 6561])

In [ ]:

# operasi trigonometri cosinus
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
np.cos(b)

array([ 0.96017029,  0.75390225, -0.14550003])

In [ ]:

# operasi trigonometri tangen
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

In [ ]:
np.tan(b)

array([-0.29100619,  0.87144798, -6.79971146])

In [ ]:

# cosinus hiperbolik
np.cosh(a)

array([ 1.54308063,  3.76219569, 10.067662  ])

In [ ]:
np.cosh(b)

array([ 201.71563612,  548.31703516, 1490.47916125])

In [ ]:

# sinus hiperbolik
np.sinh(a)

array([ 1.17520119,  3.62686041, 10.01787493])

In [ ]:
np.sinh(b)

array([ 201.71315737,  548.31612327, 1490.47882579])

In [ ]:

# operasi trigonometri sinus
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.sin(b)

array([-0.2794155 ,  0.6569866 ,  0.98935825])

In [ ]:

# tangen hiperbolik
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475])

In [ ]:

np.tanh(b)

array([0.99998771, 0.99999834, 0.99999977])

In [ ]:

# akar kuadrat
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.sqrt(b)

array([2.44948974, 2.64575131, 2.82842712])

In [ ]:
# latihan 2
import numpy as np

# Membuat array NumPy
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Penjumlahan
c = a + b
print("Penjumlahan a dan b: ", c)

# Pengurangan
d = a - b
print("Pengurangan a dan b: ", d)

# Perkalian
e = a * b
print("Perkalian a dan b: ", e)

# Pembagian
f = a / b
print("Pembagian a dan b: ", f)

# Perpangkatan
g = a ** 2
print("Perpangkatan a: ", g)

# Operasi trigonometri
h = np.sin(a)
print("Sinus dari a: ", h)

Penjumlahan a dan b:  [5 7 9]
Pengurangan a dan b:  [-3 -3 -3]
Perkalian a dan b:  [ 4 10 18]
Pembagian a dan b:  [0.25 0.4  0.5 ]
Perpangkatan a:  [1 4 9]
Sinus dari a:  [0.84147098 0.90929743 0.14112001]


In [ ]:
# latihan 3
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Penjumlahan dua array
c = a + b
print(c)

# Pengurangan dua array
d = b - a
print(d)

# Perkalian dua array
e = a * b
print(e)

# Pembagian dua array
f = b / a
print(f)

# Perpangkatan dua array
g = a ** 2
print(g)

# Modulo dua array
h = b % a
print(h)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]
[ 1  4  9 16 25]
[0 1 2 1 0]


In [ ]:
# latihan 4 
import numpy as np

# Membuat array dengan nilai sudut dalam derajat
sudut = np.array([0, 30, 45, 60, 90])

# Mengonversi sudut dari derajat ke radian
sudut_radian = np.radians(sudut)

# Menghitung nilai sin, cos, dan tan dari sudut
sin_sudut = np.sin(sudut_radian)
cos_sudut = np.cos(sudut_radian)
tan_sudut = np.tan(sudut_radian)

# Menampilkan hasil
print("Sudut dalam derajat: ", sudut)
print("Sudut dalam radian: ", sudut_radian)
print("Nilai sin: ", sin_sudut)
print("Nilai cos: ", cos_sudut)
print("Nilai tan: ", tan_sudut)

# Menghitung nilai sinh, cosh, dan tanh dari sudut hiperbolik
sinh_sudut = np.sinh(sudut_radian)
cosh_sudut = np.cosh(sudut_radian)
tanh_sudut = np.tanh(sudut_radian)

# Menampilkan hasil
print("Nilai sinh: ", sinh_sudut)
print("Nilai cosh: ", cosh_sudut)
print("Nilai tanh: ", tanh_sudut)

Sudut dalam derajat:  [ 0 30 45 60 90]
Sudut dalam radian:  [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Nilai sin:  [0.         0.5        0.70710678 0.8660254  1.        ]
Nilai cos:  [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Nilai tan:  [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
Nilai sinh:  [0.         0.54785347 0.86867096 1.24936705 2.3012989 ]
Nilai cosh:  [1.         1.14023832 1.32460909 1.60028686 2.50917848]
Nilai tanh:  [0.         0.48047278 0.6557942  0.78071444 0.91715234]


# 5.20.6 Perkalian Matrik pada Numpy

In [ ]:

# membuat array
a = np.array([[1,2,3,7], [6,7,8,9]])
# mencetak array
print(a)

[[1 2 3 7]
 [6 7 8 9]]


In [ ]:


# membuat array
b = np.array([[1,8,3,6], [9,8,3,10]])
# mencetak array
print(b)

[[ 1  8  3  6]
 [ 9  8  3 10]]


In [ ]:
c = a*b
print(c)

[[  1  64   9  36]
 [ 81  64   9 100]]


In [ ]:
# Fungsi ini digunakan untuk mengalikan dua atau lebih matriks dengan menggunakan operator @ atau np.matmul() pada NumPy.
d = np.matmul(a,e)

In [ ]:
e = np.array([[1,2],[3,4],[5,6],[7,8]])
print(e)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
f = np.matmul(a,e)
print(f)

[[ 82 100]
 [118 148]]


In [ ]:
# Latihan
import numpy as np

# membuat matriks A dan B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# perkalian matriks dengan .matmul
C = A @ B  # atau C = np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


In [ ]:
# Latihan
import numpy as np

# membuat array
a = np.array([[1,2,3,7], [6,7,8,9]])
# mencetak array
print(a)

# membuat array
b = np.array([[1,8], [3,6], [9,8], [3,10]])
# mencetak array
print(b)

# melakukan operasi perkalian matriks
c = np.matmul(a, b)
# mencetak hasil perkalian matriks
print(c)

[[1 2 3 7]
 [6 7 8 9]]
[[ 1  8]
 [ 3  6]
 [ 9  8]
 [ 3 10]]
[[ 55 114]
 [126 244]]


# 5.20.7 min, max dan sum pada Numpy

Perintah min, max dan sum cukup sering digunakan untuk mengetahui nilai
minimum, maksimum dan penjumlahan.

In [ ]:

import numpy as np

a = np.array([[4, 5, 6],
              [1, 2, 3],
              [7, 8, 9]])

[1 2 3]


In [ ]:

# ".min" adalah sebuah metode yang digunakan untuk mencari nilai minimum dari array NumPy atau salah satu sumbu array.
b = np.min(a)
print(b)

1


In [ ]:

# parameter "axis" pada metode ".min" digunakan untuk menentukan sumbu (axis) pada array NumPy multidimensi, di mana nilai minimum akan dicari.
c = np.min(a, axis=0)
print(c)

[1 2 3]


In [ ]:
d = np.min(a, axis=1)
print(d)

[4 1 7]


In [ ]:
# ".max" adalah sebuah metode yang digunakan untuk mencari nilai maksimum dari array NumPy atau salah satu sumbu array.
e = np.max(a)
print(e)

9


In [ ]:

# parameter "axis" pada metode ".max" digunakan untuk menentukan sumbu (axis) pada array NumPy multidimensi, di mana nilai maksimum akan dicari.
f = np.max(a, axis=0)
print(f)

[7 8 9]


In [ ]:
g = np.max(a, axis=1)
print(g)

[6 3 9]


In [ ]:
# "np.sum" adalah sebuah fungsi yang digunakan untuk menjumlahkan seluruh elemen pada array NumPy atau menjumlahkan elemen pada salah satu sumbu (axis) dari array NumPy.
h = np.sum(a)
print(h)

45


In [ ]:

# "np.sum" adalah sebuah fungsi yang digunakan untuk menjumlahkan seluruh elemen pada array NumPy atau menjumlahkan elemen pada salah satu sumbu (axis) dari array NumPy.
i = np.sum(a, axis=0)
print(i)

[12 15 18]


In [ ]:
j = np.sum(a, axis=1)
print(j)

[15  6 24]


In [ ]:
# Latihan
import numpy as np

# membuat array
arr = np.array([1, 3, 5, 7, 9])

# mencari nilai maksimum dari array
max_value = arr.max()

print(max_value) # output: 9

9


In [ ]:
# Latihan

import numpy as np

# membuat array 2D
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# mencari nilai maksimum dalam sumbu baris (axis=0)
max_value_axis0 = arr.max(axis=0)

print(max_value_axis0) # output: [7 8 9]

# mencari nilai maksimum dalam sumbu kolom (axis=1)
max_value_axis1 = arr.max(axis=1)

print(max_value_axis1) # output: [3 6 9]

[7 8 9]
[3 6 9]


In [ ]:
# Latihan
import numpy as np

# membuat array 2D
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# mencari nilai minimum dalam sumbu baris (axis=0)
min_value_axis0 = arr.min(axis=0)

print(min_value_axis0) # output: [1 2 3]

# mencari nilai minimum dalam sumbu kolom (axis=1)
min_value_axis1 = arr.min(axis=1)

print(min_value_axis1) # output: [1 4 7]

[1 2 3]
[1 4 7]


In [ ]:
# Latihan
import numpy as np

# membuat array
arr = np.array([1, 2, 3, 4, 5])

# menjumlahkan seluruh elemen pada array
sum_all = np.sum(arr)

print(sum_all) # output: 15

# membuat array 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# menjumlahkan elemen pada sumbu baris (axis=0)
sum_axis0 = np.sum(arr_2d, axis=0)

print(sum_axis0) # output: [12 15 18]

# menjumlahkan elemen pada sumbu kolom (axis=1)
sum_axis1 = np.sum(arr_2d, axis=1)

print(sum_axis1) # output: [ 6 15 24]

15
[12 15 18]
[ 6 15 24]
